### PR TITLE
pull request for QC package 

### PR DESCRIPTION
**Pull request by qinfangj**
new created QC package files,please review it and tell me if I need to modify something^^

### CODE REVIEW

**Comment by rmylonas** [comment]
Hi Christine,

Please commit also the summary.txt in the resources. Otherwise the test won't pass on Travis. I will accept the pull request once you added it.

Some comments:

- in getInfo() it would be better to use a regular expression instead of a split. And it would be better to give back a Tuple2[String, String] instead of an Array[String]. And it should through an exception if the date information could not be parsed. Without the date we will not be able to make a plot..

- in LoadSummarySpecs we don't need the defaultPatience. We're not making any database acesses in this test.

- well done, you're writing many test cases. :-)

- it's ok for now, but a TODO would be to parse the indexes used in getSummaryEntry from the summary.txt header

**Comment by qinfangj** [comment]
Hi,Roman,

I will commit the summary.txt from now on.

1.about method "getInfo",first I would like to tell some information which
I talked with florence.
   we make some agreement about the raw_file value will be something like  "
Hela_300ng_Qex_Dionex_00_150507_00"
   >Hela           = proteine name
   >300ng        = quantity
   >Qex            = matchine name
   >Dionex_00 =column type
   so accually I need to increase the summaryEntry elements,but I just want
to see how will be test classes and the classes work together,so I didn't
 define it in my first version.and because I still want to extract other
infomation from raw_file value,that's why I defined it as an Arrary[string].
According to your point,I should define as
Tuplen[String1,String2....Stringn],what's the better things.

2.You are right to pointing out use regular expression to parse a date,then
throw out an exceptional error when it can't be parsed.
   but for other information as I listed in 1,also need to use regular
explaination

3.I will work on getting data from the link between header and value.since
you will not be in office and I am alone,what else I should make goal to
achieve?^_^

4.Right now I didn't write DBServiece part of QC package,But I read the
code about DB in other package,I know the classes there is to create the
interface to connect with mongoDB and offer some DB method like CUD.but
where is the place to use "Insert" method?I thought after I construct a
data collections for summaryEntry,I should insert it into mongo DB to
finish the real meaning "LoadSummary",No?

thank you for your patience.

Christine

**Comment by rmylonas** [comment]
Ciao Christine,

> I will commit the summary.txt from now on.
Pull request was accepted :-)

> 1.about method "getInfo",first I would like to tell some information which
> I talked with florence.
> we make some agreement about the raw_file value will be something like "
> Hela_300ng_Qex_Dionex_00_150507_00"
> >Hela = proteine name
> >300ng = quantity
> >Qex = matchine name
> >Dionex_00 =column type
> so accually I need to increase the summaryEntry elements,but I just want
> to see how will be test classes and the classes work together,so I didn't
> define it in my first version.and because I still want to extract other
> infomation from raw_file value,that's why I defined it as an Arrary[string].
> According to your point,I should define as
> Tuplen[String1,String2....Stringn],what's the better things.
Hm.. so we're starting to get a couple of information from the raw-file. In this case I would create a new case class containing the acquisition information.

So maybe something like:
case class RawFileInformation(proteinName: String, machineName: String, ...)

and then add it to QcSummaryEntry:
case class QcSummaryEntry(rawFileInformation: RawFileInformation, MS:Int, ...)

Another thing: 
I saw that you renamed the class SummaryRef to QcSummaryEntry. But you should also rename the file itself..

> 2.You are right to pointing out use regular expression to parse a date,then
> throw out an exceptional error when it can't be parsed.
> but for other information as I listed in 1,also need to use regular
> explaination

yes, you can make one regular-expression which matches all the infos at once.
A split also works, so you can still go for the split. But a regular-expression will be much safer, since you can indicate what you expect.


> 3.I will work on getting data from the link between header and value.since
> you will not be in office and I am alone,what else I should make goal to
> achieve?^_^

You should achieve to talk to Alex. 
I would recommend you to talk to him about D3.js. You could tell him about the graphs you will need. 
He will have many ideas and you will have to follow very quickly to what he is telling you.. :-)


> 4.Right now I didn't write DBServiece part of QC package,But I read the
> code about DB in other package,I know the classes there is to create the
> interface to connect with mongoDB and offer some DB method like CUD.but
> where is the place to use "Insert" method?I thought after I construct a
> data collections for summaryEntry,I should insert it into mongo DB to
> finish the real meaning "LoadSummary",No?

Yes, you should now write the service. Look for example in ExpMongoDBService at the function insert(run: MSRun): Future[Int].
As a general hint: we're using ReactiveMongo to communicate with mongodb.

Have fun!
Roman

**Comment by qinfangj** [comment]
Thank you for accepting my pull request,Roman,

For the data structure,I am planning to do the things you wrote in the
mail,thank you for the samples
About the way to split the raw file string,can I keep the simple way as
now?there is some reasons related with user freedom when I talked with
florence,
but I can think about how to use regular expression to get the value I
want.I didn't use this Class to parse a string before but I read many in
msvis project and florence uses it in her software too so I would like to
master it.

About the DB service,the sample code you wrote to me,the Future class is
that I can understand,the Insert action will happen when the data structure
is completed,you don't have to write "call XX method" but it will be run at
some point.So that if I finish to write summaryDBService and run it,I can
see the txt data will be appealed in mongoDB which was installed in my
computer?

you give a tough goal to achieve which is to talk with Alexander,haha!
we will see...

thank you for your advices anyway
have a great vocation!!

Christine





2015-07-31 14:08 GMT+02:00 Roman Mylonas <notifications@github.com>:

**Pull request merged**
