### PR TITLE
new QcModel and QcMongoDbService classes and the tests

### PR DESCRIPTION
**Pull request by qinfangj**
I have created QcModel and QcMongoDbService classes and had the tests done.please check!

### CODE REVIEW

**Comment by TrinidadMartin** [comment]
Hello!!!!

The test are failing because of a missing file, please add it and commit it ;)

./test/resources/qc/summary1.txt (No such file or directory)

Thanks!!!

**Comment by TrinidadMartin** [comment]
Something else.... :)

For this kind of thing you should try to use val instead of var ;)

For example file LoadSummary.scala, line 52:
var rawfile = getInfo(m("Raw file"))

Cheers!!

**Comment by TrinidadMartin** [comment]
Hi again!!

In the SummaryMongoDBServices maybe the name of the collection should be more specific, something like qc.summary???

val collectionName = "summary"

Enjoy!!

**Comment by TrinidadMartin** [comment]
We have to say that we really loved the zip and map thing in the LoadSmmary.scala!!!

Well doneeeee!!!!! :+1:

**Comment by qinfangj** [comment]
Hi,thank you for your tips and comments.I have add test file summary1.txt
for specifying the name of DB services,do you think "QcSummaryMongoDBsevices" is good or just "QcMongoDBServices" is better?
and collection name can be set as "Qc.Summary" or just "QcSummary"? 
and for defining the parameter rawfileInfo,I did use " val" at the beginning but it seemed I can't pass the test,so I think maybe because of the looping each entry,parameter "rawfileInfo" has to be reset,if I use val,it won't be reset as I want,so I changed it to var and passed the test.I can try to use val and see the test result again.

**Comment by rmylonas** [comment]
Hi Christine,

> Hi,thank you for your tips and comments.I have add test file summary1.txt
> for specifying the name of DB services,do you think "QcSummaryMongoDBsevices" is good or just "QcMongoDBServices" is better?
> 
Both seems ok to me. The cool thing with Git is that we can easily rename files if we're unhappy with it.
> and collection name can be set as "Qc.Summary" or just "QcSummary"? 
> 
The general recommendation for naming mongodb collections seems to be lower-case.
So "qc.summary" should be ok.
> and for defining the parameter rawfileInfo,I did use " val" at the beginning but it seemed I can't pass the test,so I think maybe because of the looping each entry,parameter "rawfileInfo" has to be reset,if I use val,it won't be reset as I want,so I changed it to var and passed the test.I can try to use val and see the test result again
> 
> 

Hm.. I'm surprised. I think it should work with "val" as well..

cheers
Roman

**Comment by qinfangj** [comment]
Hi,Roman,can you see I made some changes for QC and committed them.
1.change var -> val in LoadSummary.scala 
 2.played the date type for QcDate but now have changed back.
I am not sure if now I am doing a pull request.

Christine

**Comment by rmylonas** [comment]
Hi Christine,

Thanks for your pull request. We'll look at it this afternoon together with Trini.

cheers
Roman

**Comment by TrinidadMartin** [comment]
Hello!!!!!

The test are not working anymore... It is because of a library we changed last week so, please, can you do a pull to update your project, merge the changes you made in the branch and do the pull request again????

Thanks!!!!

Trini

**Comment by qinfangj** [comment]
Hi,Trinidad,from my commitments I have only changed a few comments for the packages which was not about QC,it was made by Alexander last week when he came to teach me something in my computer. So sorry if that it caused the test didn't work anymore.I have merged one file ExpMongoDBServices comments and please check again.

**Comment by TrinidadMartin** [comment]
Done!!!

Good job!!! ;)

**Pull request merged**
